version: '3.8'

services:
  finbuddy-backend:
    build:
      context: ./supabase/functions
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - HF_API_KEY=${HF_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./supabase/functions:/app
    restart: unless-stopped

  # Optional: Local Supabase instance
  supabase:
    image: supabase/supabase:latest
    ports:
      - "54321:54321"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data: