# Render Configuration for FinBuddy Full Stack App
# This file is used by Render.com for deployment

services:
  - type: web
    name: finbuddy-fullstack
    env: node
    plan: free
    buildCommand: npm run build:fullstack
    startCommand: npm run free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
